require("sahith.core.colorscheme")
require("sahith.core.keymaps")
require("sahith.core.options")
require("sahith.plugins-setup")
require("sahith.plugins.comment")
require("sahith.plugins.nvim-tree")
require("sahith.plugins.lualine")
require("sahith.plugins.nvim-cmp")
require("sahith.plugins.lsp.mason")
require("sahith.plugins.lsp.lspsaga")
require("sahith.plugins.lsp.lspconfig")
require("sahith.plugins.lsp.null-is") -- actually the plugin name is null ls
require("sahith.plugins.autopairs")
require("sahith.plugins.treesitter")
require("sahith.plugins.toggleterm")
